# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('code', models.TextField(blank=True, default='print("test")')),
                ('error', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CodeCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('attribute', models.CharField(max_length=256)),
                ('ttl', models.IntegerField(default=15)),
                ('check_regex', models.BinaryField(default=b'(.*)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CodeCheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='codecheck',
            name='codechecklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='secode.CodeCheckList'),
        ),
        migrations.AddField(
            model_name='code',
            name='codechecklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='secode.CodeCheckList'),
        ),
    ]
