# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codecheck',
            name='attribute',
            field=models.CharField(default='', max_length=256),
        ),
    ]
